language: android
jdk:
- oraclejdk8
before_install:
  - if [ ! -d ./android-ndk-r10e ];then wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin 1>/dev/null ; sudo chmod a+x android-ndk-r10e-linux-x86_64.bin ; ./android-ndk-r10e-linux-x86_64.bin > /dev/null ; fi
  - export ANDROID_NDK=/home/travis/build/hjiayz/build_expo/android-ndk-r10e
  - git clone https://github.com/expo/expo.git
  - yes | sdkmanager "build-tools;28.0.1"
  - yes | sdkmanager "platform-tools"
  - yes | sdkmanager "tools"
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "extras;android;m2repository"
script:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  - nvm install node
  - nvm use node
  - npm install gulp-cli -g
  - cd expo
  - cd js
  - npm install
  - cd ..
  - cd tools-public
  - npm install
  - cd ..
  - cd android
  - ./run.sh
  - cd ..
  - cd tools-public
  - gulp android-shell-app --url a.b.c --sdkVersion 25
  - cd ../../
  - cp /tmp/shell-debug.apk expo.apk
deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  file: expo.apk
  skip_cleanup: true
  on:
tags: true
