language: node
before_install:
  - git clone https://github.com/expo/expo.git
  - if [ ! -d ./android-ndk-r10e ];then wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin ; sudo chmod a+x android-ndk-r10e-linux-x86_64.bin ; ./android-ndk-r10e-linux-x86_64.bin > /dev/null ; fi
  - export ndk.dir= ./android-ndk-r10e
script:
  - npm install gulp-cli -g
  - cd android
  - ./run.sh
  - cd ..
deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  file: expo.apk
  skip_cleanup: true
  on:
tags: true
