language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
before_install:
  - git clone https://github.com/expo/expo.git
  - export ANDROID_NDK=/home/travis/build/hjiayz/build_expo/android-ndk-r10e
  - sudo apt-get install node
script:
  - npm install gulp-cli -g
  - cd expo
  - cd js
  - npm install
  - cd ..
  - cd tools-public
  - npm install
  - cd ..
  - cd android
  - ./run.sh
  - cd ..
  - cd tools-public
  - gulp android-shell-app --url a.b.c --sdkVersion 25
  - cd ../../
  - cp /tmp/shell-debug.apk expo.apk
deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  file: expo.apk
  skip_cleanup: true
  on:
tags: true
