language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
before_install:
  - git clone https://github.com/expo/expo.git
  - if [ ! -d ./android-ndk-r10e ];then wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin ; sudo chmod a+x android-ndk-r10e-linux-x86_64.bin ; ./android-ndk-r10e-linux-x86_64.bin > /dev/null ; fi
  - export ANDROID_NDK=/home/travis/build/hjiayz/build_expo/android-ndk-r10e
  - sudo apt-get install node
script:
  - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar -zxvf android-sdk_r24.4.1-linux.tgz
  - echo y|./android-sdk-linux/tools/android update sdk -u -a -s -t 1
  - echo y|./android-sdk-linux/tools/android update sdk -u -a -s -t 2
  - echo y|./android-sdk-linux/tools/android update sdk -u -a -s -t 3
  - echo y|./android-sdk-linux/tools/android update sdk -u -a -s -t 4
  - export ANDROID_SDK=/home/travis/build/hjiayz/build_expo/android-sdk-linux
  - export ANDROID_HOME=/home/travis/build/hjiayz/build_expo/android-sdk-linux
  - npm install gulp-cli -g
  - cd expo
  - cd js
  - npm install
  - cd ..
  - cd tools-public
  - npm install
  - cd ..
  - cd android
  - ./run.sh
  - cd ..
  - cd tools-public
  - gulp android-shell-app --url a.b.c --sdkVersion 25
  - cd ../../
  - cp /tmp/shell-debug.apk expo.apk
deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  file: expo.apk
  skip_cleanup: true
  on:
tags: true
